name: pipeline1
tasks:
- name: Preprocessing-Bias Subtraction
  steps:
  - checked: 'True'
    configuration:
    - {default: '%%BiasImage', id: BiasImage1, label: BiasImage, type: textfield}
    - {default: step1.pkl, id: OutputFile1, label: OutputFile, type: textfield}
    name: Bias Subtraction
    source: ProcAlgs
  - checked: 'True'
    configuration:
    - {default: step1.pkl, id: OutputFile2, label: OutputFile, type: textfield}
    name: Get RMS
    source: MonAlgs
  - checked: 'True'
    configuration:
    - {default: '3.0', id: Width1, label: Width, type: textfield}
    - {default: step1.pkl, id: OutputFile3, label: OutputFile, type: textfield}
    name: Count Pixels
    source: MonAlgs
- name: Preprocessing-Dark Subtraction
  steps:
  - checked: 'True'
    configuration:
    - {default: '%%DarkImage', id: DarkImage1, label: DarkImage, type: textfield}
    - {default: step2.pkl, id: OutputFile4, label: OutputFile, type: textfield}
    name: Dark Subtraction
    source: ProcAlgs
  - checked: 'True'
    configuration:
    - {default: step2.pkl, id: OutputFile5, label: OutputFile, type: textfield}
    name: Get RMS
    source: MonAlgs
  - checked: 'True'
    configuration:
    - {default: '3.0', id: Width2, label: Width, type: textfield}
    - {default: step2.pkl, id: OutputFile6, label: OutputFile, type: textfield}
    name: Count Pixels
    source: MonAlgs
- name: Preprocessing-Pixel Flattening
  steps:
  - checked: 'True'
    configuration:
    - {default: '%%PixelFlat', id: PixelFlat1, label: PixelFlat, type: textfield}
    - {default: step3.pkl, id: OutputFile7, label: OutputFile, type: textfield}
    name: Pixel Flattening
    source: ProcAlgs
  - checked: 'True'
    configuration:
    - {default: step3.pkl, id: OutputFile8, label: OutputFile, type: textfield}
    name: Get RMS
    source: MonAlgs
  - checked: 'True'
    configuration:
    - {default: '3.0', id: Width3, label: Width, type: textfield}
    - {default: step3.pkl, id: OutputFile9, label: OutputFile, type: textfield}
    name: Count Pixels
    source: MonAlgs
- name: Boxcar Extration
  steps:
  - checked: 'True'
    configuration:
    - default: r
      id: Band1
      items: [g, r, i, z]
      label: Band
      type: combobox
    - {default: '2.5', id: BoxWidth1, label: BoxWidth, type: textfield}
    - {default: '0.5', id: DeltaW1, label: DeltaW, type: textfield}
    - {default: '%%FiberMap', id: FiberMap1, label: FiberMap, type: textfield}
    - {default: '%%PSFFile', id: PSFFile1, label: PSFFile, type: textfield}
    - {default: '0', id: Spectrograph1, label: Spectrograph, type: textfield}
    - {default: '7741', id: Wmax1, label: Wmax, type: textfield}
    - {default: '5625', id: Wmin1, label: Wmin, type: textfield}
    - {default: step4.pkl, id: OutputFile10, label: OutputFile, type: textfield}
    name: Boxcar Extraction
    source: ProcAlgs
  - checked: 'True'
    configuration:
    - {default: '%%FiberMap', id: FiberMap2, label: FiberMap, type: textfield}
    - {default: None, id: Wmax2, label: Wmax, type: textfield}
    - {default: None, id: Wmin2, label: Wmin, type: textfield}
    - {default: step4.pkl, id: OutputFile11, label: OutputFile, type: textfield}
    name: Find Sky Continuum
    source: MonAlgs
  - checked: 'True'
    configuration:
    - {default: step4.pkl, id: OutputFile12, label: OutputFile, type: textfield}
    name: Calculate Signal-to-Noise ratio
    source: MonAlgs
