PipeLine:
- OutputFile: step1.pkl
  StepName: Preprocessing-Bias Subtraction
  Steps:
  - ModuleName: ProcAlgs
    Name: Bias Subtraction
    kwargs: {BiasImage: '%%BiasImage'}
  - ModuleName: MonAlgs
    Name: Get RMS
    kwargs: {}
  - ModuleName: MonAlgs
    Name: Count Pixels
    kwargs: {Width: '3.0'}
- OutputFile: step2.pkl
  StepName: Preprocessing-Dark Subtraction
  Steps:
  - ModuleName: ProcAlgs
    Name: Dark Subtraction
    kwargs: {DarkImage: '%%DarkImage'}
  - ModuleName: MonAlgs
    Name: Get RMS
    kwargs: {}
  - ModuleName: MonAlgs
    Name: Count Pixels
    kwargs: {Width: '3.0'}
- OutputFile: step3.pkl
  StepName: Preprocessing-Pixel Flattening
  Steps:
  - ModuleName: ProcAlgs
    Name: Pixel Flattening
    kwargs: {PixelFlat: '%%PixelFlat'}
  - ModuleName: MonAlgs
    Name: Get RMS
    kwargs: {}
  - ModuleName: MonAlgs
    Name: Count Pixels
    kwargs: {Width: '3.0'}
- OutputFile: step4.pkl
  StepName: Boxcar Extration
  Steps:
  - ModuleName: ProcAlgs
    Name: Boxcar Extraction
    kwargs: {Band: r, BoxWidth: '2.5', DeltaW: '0.5', FiberMap: '%%FiberMap', PSFFile: '%%PSFFile',
      Spectrograph: '0', Wmax: '7741', Wmin: '5625'}
  - ModuleName: MonAlgs
    Name: Find Sky Continuum
    kwargs: {FiberMap: '%%FiberMap', Wmax: None, Wmin: None}
  - ModuleName: MonAlgs
    Name: Calculate Signal-to-Noise ratio
    kwargs: {}
